
TESTS=\
	12c10_7f.prg \
	12c11_7f.prg \
	12c13_7f.prg \
	12c14_7f.prg \
    12c10.prg \
    12c11.prg \
    12c12.prg \
    12c13.prg \
    12c14.prg \
    12c15.prg \
    12c16.prg \
    12c119.prg \
    12c139.prg \
	12c14485-0_7f.prg \
	12c14485-1_7f.prg \
	12c14485-4_7f.prg \
    12c14485-0.prg \
    12c14485-3.prg \
    12c14485-19.prg \
    12c14485-39.prg \
	12c1gen-0_7f.prg \
	12c1gen-1_7f.prg \
	12c1gen-4_7f.prg \
    12c1gen-0.prg \
    12c1gen-3.prg \
    12c1gen-19.prg \
    12c1gen-39.prg \
        \
	12c20_7f.prg \
	12c21_7f.prg \
	12c24_7f.prg \
    12c20.prg \
    12c23.prg \
    12c219.prg \
    12c239.prg \
	12c24485-0_7f.prg \
	12c24485-1_7f.prg \
	12c24485-4_7f.prg \
    12c24485-0.prg \
    12c24485-3.prg \
    12c24485-19.prg \
  	12c24485-39.prg \
	12c2gen-0_7f.prg \
	12c2gen-1_7f.prg \
	12c2gen-4_7f.prg \
    12c2gen-0.prg \
    12c2gen-3.prg \
    12c2gen-19.prg \
    12c2gen-39.prg \

all: $(TESTS)

12c10_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=0 -DINTERACTIVEMODE=0 -o 12c10_7f.prg cia-sdr-icr-v3.asm
12c11_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=1 -DINTERACTIVEMODE=0 -o 12c11_7f.prg cia-sdr-icr-v3.asm
12c13_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=3 -DINTERACTIVEMODE=0 -o 12c13_7f.prg cia-sdr-icr-v3.asm
12c14_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=4 -DINTERACTIVEMODE=0 -o 12c14_7f.prg cia-sdr-icr-v3.asm
12c10.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=0 -DINTERACTIVEMODE=1 -o 12c10.prg    cia-sdr-icr-v3.asm
12c11.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=1 -DINTERACTIVEMODE=1 -o 12c11.prg    cia-sdr-icr-v3.asm
12c12.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=2 -DINTERACTIVEMODE=1 -o 12c12.prg    cia-sdr-icr-v3.asm
12c13.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=3 -DINTERACTIVEMODE=1 -o 12c13.prg    cia-sdr-icr-v3.asm
12c14.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=4 -DINTERACTIVEMODE=1 -o 12c14.prg    cia-sdr-icr-v3.asm
12c15.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=5 -DINTERACTIVEMODE=1 -o 12c15.prg    cia-sdr-icr-v3.asm
12c16.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=6 -DINTERACTIVEMODE=1 -o 12c16.prg    cia-sdr-icr-v3.asm
12c119.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=19 -DINTERACTIVEMODE=1 -o 12c119.prg  cia-sdr-icr-v3.asm
12c139.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=1 -DBAUDRATE=39 -DINTERACTIVEMODE=1 -o 12c139.prg  cia-sdr-icr-v3.asm

12c14485-0_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=0 -DBAUDRATE=0 -DINTERACTIVEMODE=0 -o 12c14485-0_7f.prg cia-sdr-icr-v3.asm
12c14485-1_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=0 -DBAUDRATE=1 -DINTERACTIVEMODE=0 -o 12c14485-1_7f.prg cia-sdr-icr-v3.asm
12c14485-4_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=0 -DBAUDRATE=4 -DINTERACTIVEMODE=0 -o 12c14485-4_7f.prg cia-sdr-icr-v3.asm
12c14485-0.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=0 -DBAUDRATE=0 -DINTERACTIVEMODE=1 -o 12c14485-0.prg cia-sdr-icr-v3.asm
12c14485-3.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=0 -DBAUDRATE=3 -DINTERACTIVEMODE=1 -o 12c14485-3.prg cia-sdr-icr-v3.asm
12c14485-19.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=0 -DBAUDRATE=19 -DINTERACTIVEMODE=1 -o 12c14485-19.prg cia-sdr-icr-v3.asm
12c14485-39.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=0 -DBAUDRATE=39 -DINTERACTIVEMODE=1 -o 12c14485-39.prg cia-sdr-icr-v3.asm

12c1gen-0_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=2 -DBAUDRATE=0 -DINTERACTIVEMODE=0 -o 12c1gen-0_7f.prg cia-sdr-icr-v3.asm
12c1gen-1_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=2 -DBAUDRATE=1 -DINTERACTIVEMODE=0 -o 12c1gen-1_7f.prg cia-sdr-icr-v3.asm
12c1gen-4_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=2 -DBAUDRATE=4 -DINTERACTIVEMODE=0 -o 12c1gen-4_7f.prg cia-sdr-icr-v3.asm
12c1gen-0.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=2 -DBAUDRATE=0 -DINTERACTIVEMODE=1 -o 12c1gen-0.prg cia-sdr-icr-v3.asm
12c1gen-3.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=2 -DBAUDRATE=3 -DINTERACTIVEMODE=1 -o 12c1gen-3.prg cia-sdr-icr-v3.asm
12c1gen-19.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=2 -DBAUDRATE=19 -DINTERACTIVEMODE=1 -o 12c1gen-19.prg cia-sdr-icr-v3.asm
12c1gen-39.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=1 -DCIATYPE=2 -DBAUDRATE=39 -DINTERACTIVEMODE=1 -o 12c1gen-39.prg cia-sdr-icr-v3.asm



12c20_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=1 -DBAUDRATE=0 -DINTERACTIVEMODE=0 -o 12c20_7f.prg cia-sdr-icr-v3.asm
12c21_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=1 -DBAUDRATE=1 -DINTERACTIVEMODE=0 -o 12c21_7f.prg cia-sdr-icr-v3.asm
12c24_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=1 -DBAUDRATE=4 -DINTERACTIVEMODE=0 -o 12c24_7f.prg cia-sdr-icr-v3.asm
12c20.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=1 -DBAUDRATE=0 -DINTERACTIVEMODE=1 -o 12c20.prg cia-sdr-icr-v3.asm
12c23.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=1 -DBAUDRATE=3 -DINTERACTIVEMODE=1 -o 12c23.prg cia-sdr-icr-v3.asm
12c219.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=1 -DBAUDRATE=19 -DINTERACTIVEMODE=1 -o 12c219.prg cia-sdr-icr-v3.asm
12c239.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=1 -DBAUDRATE=39 -DINTERACTIVEMODE=1 -o 12c239.prg cia-sdr-icr-v3.asm


12c24485-0_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=0 -DBAUDRATE=0 -DINTERACTIVEMODE=0 -o 12c24485-0_7f.prg cia-sdr-icr-v3.asm
12c24485-1_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=0 -DBAUDRATE=1 -DINTERACTIVEMODE=0 -o 12c24485-1_7f.prg cia-sdr-icr-v3.asm
12c24485-4_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=0 -DBAUDRATE=4 -DINTERACTIVEMODE=0 -o 12c24485-4_7f.prg cia-sdr-icr-v3.asm
12c24485-0.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=0 -DBAUDRATE=0 -DINTERACTIVEMODE=1 -o 12c24485-0.prg cia-sdr-icr-v3.asm
12c24485-3.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=0 -DBAUDRATE=3 -DINTERACTIVEMODE=1 -o 12c24485-3.prg cia-sdr-icr-v3.asm
12c24485-19.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=0 -DBAUDRATE=19 -DINTERACTIVEMODE=1 -o 12c24485-19.prg cia-sdr-icr-v3.asm
12c24485-39.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=0 -DBAUDRATE=39 -DINTERACTIVEMODE=1 -o 12c24485-39.prg cia-sdr-icr-v3.asm

12c2gen-0_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=2 -DBAUDRATE=0 -DINTERACTIVEMODE=0 -o 12c2gen-0_7f.prg cia-sdr-icr-v3.asm
12c2gen-1_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=2 -DBAUDRATE=1 -DINTERACTIVEMODE=0 -o 12c2gen-1_7f.prg cia-sdr-icr-v3.asm
12c2gen-4_7f.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=2 -DBAUDRATE=4 -DINTERACTIVEMODE=0 -o 12c2gen-4_7f.prg cia-sdr-icr-v3.asm
12c2gen-0.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=2 -DBAUDRATE=0 -DINTERACTIVEMODE=1 -o 12c2gen-0.prg cia-sdr-icr-v3.asm
12c2gen-3.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=2 -DBAUDRATE=3 -DINTERACTIVEMODE=1 -o 12c2gen-3.prg cia-sdr-icr-v3.asm
12c2gen-19.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=2 -DBAUDRATE=19 -DINTERACTIVEMODE=1 -o 12c2gen-19.prg cia-sdr-icr-v3.asm
12c2gen-39.prg: cia-sdr-icr-v3.asm
	acme -f cbm -DCIA=2 -DCIATYPE=2 -DBAUDRATE=39 -DINTERACTIVEMODE=1 -o 12c2gen-39.prg cia-sdr-icr-v3.asm

generate:
	cc generate.c -o generate

	
rename: all
	rename sdr-icr- "" *.prg

clean:
	rm -f *.prg generate
